<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_State  Province  Region_vfb-13zip</name>
   <tag></tag>
   <elementGuidId>132ed4c8-78de-44ab-900b-58ae54e3e4d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-13-zip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-13-zip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17f86b47-b4c7-4772-89cc-cef2b0d95934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>029e4314-88f4-4358-bfef-f13a579fc857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-13[zip]</value>
      <webElementGuid>a92c5b8f-cef9-4f66-9f3c-71b2e736b0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-13-zip</value>
      <webElementGuid>3594c25f-e7af-45da-908f-ba804c5d1b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>27d459f0-518e-471e-88d7-f5de41675b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text vfb-medium  </value>
      <webElementGuid>0ddc47fd-a677-4617-b450-e0eca9049e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-13-zip&quot;)</value>
      <webElementGuid>ec875d7d-bd84-49fa-b7dd-731f5f6ca948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-13-zip']</value>
      <webElementGuid>8a36fa1f-cad6-4f80-96fd-407a9fdebc24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-13']/div/span[5]/input</value>
      <webElementGuid>64524898-42e6-4917-9022-132d43ec1f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/input</value>
      <webElementGuid>a8a78274-91c5-468e-8d74-d54740526564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-13[zip]' and @id = 'vfb-13-zip']</value>
      <webElementGuid>d52c5741-7a9d-4e21-9af9-eb028ff3b264</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
