<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vfb-14</name>
   <tag></tag>
   <elementGuidId>3431b394-27e8-404e-8706-e52fe1891f0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-14']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfd43146-5e6c-417a-8f4b-ff33e441550c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e73b68d1-fb2e-4960-a4ff-380410ca659e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-14</value>
      <webElementGuid>a8e452a5-9f81-413c-a9a2-82adc38be5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-14</value>
      <webElementGuid>18560607-ad8c-453d-b7f1-0f119be65309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium  required  email </value>
      <webElementGuid>55f1bd8a-0294-4b15-8ecf-0a0587773366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-14&quot;)</value>
      <webElementGuid>0ad17a63-f025-46e6-b6df-129fd888435c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-14']</value>
      <webElementGuid>2ba570f1-476a-4de3-8b0a-47baafea3d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-14']/input</value>
      <webElementGuid>e526fc1c-87ec-4c18-b1a9-fa68f33492d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/input</value>
      <webElementGuid>2adba172-6adf-456e-82ba-493766e53542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'vfb-14' and @id = 'vfb-14']</value>
      <webElementGuid>bcc789cd-a7b8-49f9-baaa-4b30b86b77a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
