<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_First Name</name>
   <tag></tag>
   <elementGuidId>3ff3af78-e58c-4acb-9b13-9ca3db94dbb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.vfb-desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='item-vfb-5']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3dda1c91-2917-4398-8fe8-4c6587136b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>vfb-5</value>
      <webElementGuid>d35da6de-3c08-4345-8ebd-d2fec4c2d62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-desc</value>
      <webElementGuid>eafd40f8-e6a2-40d5-941b-285ee3095247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First Name  *</value>
      <webElementGuid>5f42e18a-9af9-49c2-a411-da18112acfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-vfb-5&quot;)/label[@class=&quot;vfb-desc&quot;]</value>
      <webElementGuid>c9e41806-bb84-4af3-ae28-6a652325d0da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-5']/label</value>
      <webElementGuid>d627ff1d-a0f7-499c-82d6-809065add6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register For Demo'])[1]/following::label[1]</value>
      <webElementGuid>0403cccd-fbbb-44f3-8b04-4f1846bc131a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java'])[2]/following::label[1]</value>
      <webElementGuid>d71269a8-480d-4cc1-8141-d1b7d80a8938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='First Name']/parent::*</value>
      <webElementGuid>fd709858-1f82-4fe6-a2f5-735a39c50637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>c084929d-9a54-45e8-bf7f-bf167649584e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'First Name  *' or . = 'First Name  *')]</value>
      <webElementGuid>50a39ca4-8258-4506-b8b1-1405d66c2237</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
