<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_First Name</name>
   <tag></tag>
   <elementGuidId>5af71918-295a-4951-8ef6-be1b7a46e5a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#item-vfb-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='item-vfb-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7fb5b94a-ccc6-4cd7-9996-fc37efcb8526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-item vfb-item-text  </value>
      <webElementGuid>f46ccd4f-9a94-41b2-a93a-a05275eb61c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item-vfb-5</value>
      <webElementGuid>d4b02345-f1af-4d3e-9067-ba0157993c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First Name  *</value>
      <webElementGuid>0131bfe1-8da4-443e-bcd9-1835ff2b508c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-vfb-5&quot;)</value>
      <webElementGuid>c744aa38-babf-42f7-a240-702d983907ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-5']</value>
      <webElementGuid>67ce9f34-a0bd-4c76-a7f6-5849474aaed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='item-vfb-1']/ul/li</value>
      <webElementGuid>00a841cc-594d-4167-b1a2-1445b99d3c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register For Demo'])[1]/following::li[1]</value>
      <webElementGuid>0efd8cd1-eda2-4159-93ee-2dab40a32430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java'])[2]/following::li[1]</value>
      <webElementGuid>01874fe7-a4d9-4eb6-802f-ecf519f87bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/ul/li</value>
      <webElementGuid>5d560b7b-751a-4533-8795-94a43bb0e648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'item-vfb-5' and (text() = 'First Name  *' or . = 'First Name  *')]</value>
      <webElementGuid>382bedb4-295c-410f-a571-247ae262269e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
